CREATE TABLE projects (
    name varchar PRIMARY KEY,
    slug varchar,
    icon_uri varchar,
    ratelimit int,
    min_pipeline_version varchar,
    deadline timestamptz,
    public bool DEFAULT false,
    paused bool DEFAULT false
);
-- If an operator is not happy with the data for an item, they can set
-- 'succeeded' back to 'should_handout' to get it assigned to another
-- worker.
CREATE TYPE item_status AS ENUM ('should_handout', 'handed_out', 'succeeded', 'scrapped');
CREATE TABLE items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project varchar REFERENCES projects(name),
    item varchar NOT NULL,
    status item_status NOT NULL DEFAULT 'should_handout',
    expected_duration interval NOT NULL DEFAULT '1 day',
    priority int NOT NULL DEFAULT 1,

    UNIQUE (project, item)
);
CREATE DOMAIN username AS varchar(32) CHECK (VALUE ~ '^\w{3,24}$');
CREATE TABLE accounts (
    username username PRIMARY KEY,
    password_hash varchar NOT NULL
);
CREATE TYPE handout_status AS ENUM ('in_progress', 'abandoned', 'errored', 'uploading', 'succeeded');
CREATE TABLE handouts (
    item_id bigint REFERENCES items(id),
    handed_time timestamptz NOT NULL DEFAULT now(),
    last_heartbeat timestamptz NOT NULL DEFAULT now(),
    status handout_status NOT NULL,
    finished_time timestamptz CHECK (finished_time >= handed_time), -- NULL if not finished
    upload_size int CHECK (upload_size >= 0),
    username username NOT NULL,
    script_version varchar NOT NULL,

    PRIMARY KEY (item_id, handed_time)
);
CREATE TABLE sessions (
    user_for varchar references accounts(username),
    session_name varchar,
    token varchar PRIMARY KEY,
    expire int
);
